spring.application.name=backend-assignment
server.port=8081
# Database
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

dummy.api.base.url=https://dummyjson.com/
dummy.api.userEndpoint=users

# Enable Circuit Breaker for external API calls
resilience4j.circuitbreaker.instances.externalUserService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.externalUserService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.externalUserService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.externalUserService.permittedNumberOfCallsInHalfOpenState=4
resilience4j.circuitbreaker.instances.externalUserService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.externalUserService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.externalUserService.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.externalUserService.slowCallDurationThreshold=5


logging.level.io.github.resilience4j.circuitbreaker=DEBUG


# Enable Hibernate SQL logging
spring.jpa.show-sql=false

# Format SQL queries for better readability
spring.jpa.properties.hibernate.format_sql=info

# Log parameter values (Recommended)
spring.jpa.properties.hibernate.type=info
